<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BCBBTQ1" failures="0" tests="4" name="FunctionalTest(Chrome)" time="15.943" errors="0" timestamp="2023-04-27T17:31:23 IST">
  <testcase classname="test.LoginWith_Standard_Users" name="@AfterMethod getTestResult" time="0.009">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "this.test" is null
at test.LoginWith_Standard_Users.getTestResult(LoginWith_Standard_Users.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod getTestResult -->
  <testcase classname="test.Loginwith_locked_out_user" name="@AfterMethod getTestResult" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "this.test" is null
at test.Loginwith_locked_out_user.getTestResult(Loginwith_locked_out_user.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod getTestResult -->
  <testcase classname="test.LoginWith_problem_user" name="@AfterMethod getTestResult" time="0.0">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "this.test" is null
at test.LoginWith_problem_user.getTestResult(LoginWith_problem_user.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod getTestResult -->
  <testcase classname="test.LoginWith_performance_glitch_user" name="@AfterMethod getTestResult" time="0.002">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "this.test" is null
at test.LoginWith_performance_glitch_user.getTestResult(LoginWith_performance_glitch_user.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod getTestResult -->
  <testcase classname="test.LoginWith_Standard_Users" name="@AfterTest publishReports" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterTest publishReports -->
  <testcase classname="test.LoginWith_performance_glitch_user" name="@AfterTest publishReports" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterTest publishReports -->
  <testcase classname="test.LoginWith_problem_user" name="@AfterTest publishReports" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterTest publishReports -->
  <testcase classname="test.Loginwith_locked_out_user" name="@AfterTest publishReports" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterTest publishReports -->
  <testcase classname="test.LoginWith_Standard_Users" name="verifyLoginWithStandaredUsers" time="0.44"/>
  <testcase classname="test.Loginwith_locked_out_user" name="verifyLoginWith_locked_out_user" time="0.309"/>
  <testcase classname="test.LoginWith_problem_user" name="verifyLoginWithproblem_user" time="0.603"/>
  <testcase classname="test.LoginWith_performance_glitch_user" name="verifyLoginWithperformance_glitch_user" time="5.518"/>
</testsuite> <!-- FunctionalTest(Chrome) -->
